discord:
  token: null
  guild: null
module:
  chat:
    discord:
      channel: null
  status:
    errorTolerance: 10
    interval: 100
    discord:
      channel: null
      message: null
    worlds:
      world: 'Overworld'
      world_nether: 'Nether'
      world_the_end: 'End'
    emotes:
      world: ':deciduous_tree:'
      world_nether: ':fire:'
      world_the_end: ':skull:'