# The Discord bot token
discordToken: "null"
# The amount of messages that are kept in memory (important for replies,
# should be at least 100 or unexpected behaviour may occur)
messageBacklog: 1000
# Allow the use of custom emojis as player name prefix
useEmoji: true
# Show Discord online status in-game
useOnlineStatus: true
# Allow users to use the bots' private chat
directMessages: true
# Show "XY is typing..." over the actionbar
typingIndicator: false

# TODO: move this to the wiki (maybe use a table to visualize which can use which)
format:
  # The in-game chat format. The following placeholders will be replaced by the plugin:
  # %user%    - Universal username
  # %player%  - Minecraft player name
  # %discord% - Discord user name
  # %message% - Content of the message
  minecraftChat:
    # Minecraft -> Minecraft
    minecraft: "§6%user%§8:  §7%message%"
    # Discord -> Minecraft
    discord: "§9%user%§8:  §7%message%"
  # The Discord chat format. The following placeholders will be replaced by the plugin:
  # %user%    - Universal username
  # %player%  - Minecraft player name
  # %mention% - Discord user as a @mention (Only recommended for embeds, as they don't ping the user)
  # %message% - Content of the message
  # %emote%   - The player emoji (Required useEmoji to be enabled)
  discordChat:
    # Discord -> Minecraft
    minecraft: "%emote% **__%player%__:**  %content%"
    # Discord -> Discord
    # TODO: docs
    # TODO: more options (name, effective name, tag, guild, channel, ...)
    discord: "%guild% **__%discord%__:** %content%"
