name: DiscordSync
main: de.eldritch.spigot.DiscordSync.DiscordSync
version: ${project.version}

api-version: 1.18

description: Synchronize Minecraft's ingame chat with a Discord channel, check the server's status via Discord, link accounts and much more!

author: TurtleException
website: https://github.com/TurtleException/DiscordSync

commands:
  verify:
    description: Verbindet das Minecraft-Konto mit dem angegebenen Discord-Account
    usage: /verify <Discord Name>