name: DiscordSync
main: de.turtleboi.spigot.dsync.DiscordSync
load: STARTUP

version: ${project.version}

api-version: 1.20
description: ${project.description}

author: TurtleException
website: https://github.com/TurtleException/DiscordSync

commands:
  channel:
    description: "General command to control channels" # TODO
    usage: "/channel <info|switch|list|create|delete|mute>" # TODO
