name: DiscordSync
main: de.eldritch.spigot.discord_sync.DiscordSync
version: ${project.version}

api-version: 1.18.1

description: Synchronize Minecraft's ingame chat with a Discord channel, check the server's status via Discord, link accounts and much more!

author: TurtleException
website: https://github.com/TurtleException/DiscordSync