name: DiscordSync
main: de.turtle_exception.discordsync.DiscordSync
version: ${project.version}

api-version: 1.19.3

description: Synchronize Minecraft's in-game chat with a Discord channel, check the server's status via Discord, link accounts and much more!

author: TurtleException
website: https://github.com/TurtleException/DiscordSync
